sources:
  docker:
    type: docker_logs
    exclude_containers:
      - "vector"
    auto_partial_merge: true

transforms:
  filter_logs:
    type: filter
    inputs:
      - docker
    condition: '.container_name == "pocketbase" || .container_name == "caddy"'

sinks:
  logfire:
    type: opentelemetry
    inputs:
      - filter_logs
    protocol:
      type: "http"
      uri: "https://logfire-eu.pydantic.dev"
      encoding:
        codec: "otlp"
      request:
        headers:
          Authorization: "Bearer ${LOGFIRE_TOKEN}"
