sources:
  docker:
    type: docker_logs
    exclude_containers:
      - "vector"
    auto_partial_merge: true

transforms:
  filter_logs:
    type: filter
    inputs:
      - docker
    condition: '.container_name == "pocketbase" || .container_name == "caddy"'

  format_otlp:
    type: remap
    inputs:
      - filter_logs
    source: |
      . = {
        "resourceLogs": [{
          "resource": {
            "attributes": [
              { "key": "service.name", "value": { "stringValue": .container_name } },
              { "key": "container.id", "value": { "stringValue": .container_id } },
              { "key": "host.name", "value": { "stringValue": .host } }
            ]
          },
          "scopeLogs": [{
            "logRecords": [{
              "timeUnixNano": to_unix_timestamp!(.timestamp, "nanoseconds"),
              "body": { "stringValue": .message },
              "attributes": [
                { "key": "stream", "value": { "stringValue": .stream } }
              ]
            }]
          }]
        }]
      }

sinks:
  logfire:
    type: opentelemetry
    inputs:
      - format_otlp
    protocol:
      type: "http"
      uri: "https://logfire-eu.pydantic.dev/v1/logs"
      encoding:
        codec: "otlp"
      request:
        headers:
          Authorization: "Bearer ${LOGFIRE_TOKEN}"
